name: flutter_quote_wallpaper_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.14.3
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icons/icon_2.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/icon_2.png"


flutter:
  uses-material-design: true
