name: quowally
description: "Quote Wallpaper App."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.14.3
  logger: ^2.5.0
  hydrated_bloc: ^10.0.0
  http: ^1.3.0
  rename: ^3.1.0
  flutter_switch: ^0.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  workmanager: ^0.6.0
  wallpaper_plugin:
    path: ./wallpaper_plugin


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.5.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icons/icon_2.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/icon_2.png"


flutter:
  uses-material-design: true
  assets:
    - assets/quotes/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Noto Serif
      fonts:
        - asset: assets/fonts/NotoSerif-VariableFont_wdth,wght.ttf
    - family: Sofia
      fonts:
        - asset: assets/fonts/Sofia-Regular.ttf
    - family: Domine
      fonts:
        - asset: assets/fonts/Domine-VariableFont_wght.ttf
    - family: Old Standard TT
      fonts:
        - asset: assets/fonts/OldStandardTT-Regular.ttf
    - family: Fondamento
      fonts:
        - asset: assets/fonts/Fondamento-Regular.ttf
    - family: Cormorant Infrant
      fonts:
        - asset: assets/fonts/CormorantInfant-VariableFont_wght.ttf
    - family: Cookie
      fonts:
        - asset: assets/fonts/Cookie-Regular.ttf
    - family: Tangerine
      fonts:
        - asset: assets/fonts/Tangerine-Regular.ttf
    - family: Italianno
      fonts:
        - asset: assets/fonts/Italianno-Regular.ttf
    - family: Tiro Devanagari Hindi
      fonts:
        - asset: assets/fonts/TiroDevanagariHindi-Regular.ttf
    - family: Tiro Devanagari Sanskrit
      fonts:
        - asset: assets/fonts/TiroDevanagariSanskrit-Regular.ttf
    - family: Mukta Vaani
      fonts:
        - asset: assets/fonts/MuktaVaani-Regular.ttf
    - family: Smythe
      fonts:
        - asset: assets/fonts/Smythe-Regular.ttf
    - family: Major Mono Display
      fonts:
        - asset: assets/fonts/MajorMonoDisplay-Regular.ttf
    - family: Noto Sans Mono
      fonts:
        - asset: assets/fonts/NotoSansMono-VariableFont_wdth,wght.ttf
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin-VariableFont_wdth,wght.ttf
    - family: Rubik Doodle Shadow
      fonts:
        - asset: assets/fonts/RubikDoodleShadow-Regular.ttf
    - family: Nosifer
      fonts:
        - asset: assets/fonts/Nosifer-Regular.ttf
  

